# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1noWBKL9vorD4wjbF77rTr-eOY2c03YfV
"""

import pandas as pd

df = pd.read_csv('v9_all_results.csv')

# Создаем финальный файл с нужными колонками
df['id'] = range(1, len(df) + 1)  # создаем id
df = df[['id', 'name', 'name_spec', 'price', 'experience']]  # оставляем только нужное

# Сохраняем
df.to_csv('vacancies_variant9.csv', index=False)

print(f"Создан файл с {len(df)} вакансиями")
print(df.head())

from google.colab import files
files.download('vacancies_variant9.csv')